---
layout: post
title: "Python学习：异常"
date: 2019-10-16 14:00:00 +0800
categories: Python
tags: Python 异常
---

> 摘要：Python 中的异常

## 语法格式

在 Python 中通过 try...except 来处理异常：
```python
try:
	pass
except Exception:
	# 错误类型 1
	pass
except Exception:
	# 错误类型 2
	pass
except Exception as e: 
	# 其他错误类型
	raise
else:
	pass
finally:
	pass
```

try语句按照如下方式工作：

* 首先，执行 try 子句（在关键字 try 和关键字 except 之间的语句）
* 如果没有异常发生，忽略 except 子句，try 子句执行后结束。
* 如果在执行 try 子句的过程中发生了异常，那么 try 子句余下的部分将被忽略。如果异常的类型和 except 之后的名称相符，那么对应的 except 子句将被执行。
* 如果一个异常没有与任何的 except 匹配，那么这个异常将会传递给上层的 try 中。
* else 子句必须放在所有的 except 子句之后。这个子句将在try子句没有发生任何异常的时候执行。
* finally 无论 try 语句有没有发生异常，一定会被执行。

一个except子句可以同时处理多个异常，这些异常将被放在一个括号里成为一个元组，例如：
```python
except (RuntimeError, TypeError, NameError):
        pass
```

## 抛出异常

通过 raise 语句可以抛出一个指定的异常：
```python
raise NameError("抛出一个异常")
```
控制台输出：
```sh
NameError: 抛出一个异常
```

如果并不想处理，一个简单的 raise 语句就可以再次把他抛出：
```python
try:
    raise NameError("抛出一个异常")
except NameError:
    print("捕获到一个异常")
    raise
```
控制台输出：
```sh
捕获到一个异常
Traceback (most recent call last):
  File "***", line 2, in <module>
    raise NameError("抛出一个异常")
NameError: 抛出一个异常
```

## 自定义异常

可以通过创建一个新的异常类来拥有自己的异常。异常类继承自 Exception 类，可以直接继承，或者间接继承：
```python
class MyError(Exception):

    def __init__(self, value):
        self.value = value

    def __str__(self):
        return repr(self.value)


raise MyError("自定义异常")
```
控制台输出：
```sh
Traceback (most recent call last):
  File "***", line 10, in <module>
    raise MyError("自定义异常")
__main__.MyError: '自定义异常'
```